services:
  webslayer:
    depends_on:
      ollama:
        condition: service_started
      ollama-init:
        condition: service_completed_successfully

  celery_worker:
    depends_on:
      ollama:
        condition: service_started
      ollama-init:
        condition: service_completed_successfully

  # https://hub.docker.com/r/ollama/ollama instructions how to enable GPU
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: serve

  ollama-init:
    image: curlimages/curl:latest
    environment:
      - DEFAULT_LLM_MODEL=${DEFAULT_LLM_MODEL:-llama3.1:8b-instruct-q5_0}
    depends_on:
      ollama:
        condition: service_started
    volumes:
      - ./ollama-init.sh:/ollama-init.sh
    command: sh /ollama-init.sh

volumes:
  ollama_data: 